name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check Azure Resources Existence
        run: |
          APP_SERVICE_PLAN_EXISTS=$(az appservice plan show --name asp-culinary-compass --resource-group abn --query "name" -o tsv 2>/dev/null || echo "")
          APP_SERVICE_EXISTS=$(az webapp show --name culinary-compass --resource-group abn --query "name" -o tsv 2>/dev/null || echo "")
          echo "APP_SERVICE_PLAN_EXISTS=$APP_SERVICE_PLAN_EXISTS" >> $GITHUB_ENV
          echo "APP_SERVICE_EXISTS=$APP_SERVICE_EXISTS" >> $GITHUB_ENV

      - name: Deploy Bicep template
        run: |
          if [ -z "$APP_SERVICE_PLAN_EXISTS" ] || [ -z "$APP_SERVICE_EXISTS" ]; then
            az deployment group create --resource-group abn --template-file ./infra/main.bicep --parameters appServicePlanExists=${{ env.APP_SERVICE_PLAN_EXISTS != '' }} appServiceExists=${{ env.APP_SERVICE_EXISTS != '' }}
          else
            echo "Resources already exist, skipping deployment."
          fi

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Run Maven tests
        run: mvn test
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set App Service Configuration
        run: |
          az webapp config appsettings set --resource-group abn --name culinary-compass --settings \
          SPRING_PROFILES_ACTIVE=prod \
          ADMIN_PASS=${{ secrets.ADMIN_PASS }} \
          ADMIN_USER=${{ secrets.ADMIN_USER }} \
          MONGO_URL=${{ secrets.MONGO_URL }}
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Deploy with Maven
        run: mvn clean package azure-webapp:deploy -DskipTests
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

